name: Fetch Google Sheets Data

on:
  # schedule:
  #   - cron: '0 6-23/3 * * *'  # Runs every 3 hours between 6 AM and 11 PM
  workflow_dispatch:  # This allows you to manually trigger the workflow from the Actions tab.

permissions:
  contents: write  # Ensure the workflow has write access to contents

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Ensure data directory exists
      run: mkdir -p data

    - name: Fetch Google Sheets Data
      run: |
         BASE_URL="${{ secrets.GOOGLE_SHEET_WEB_APP_URL }}"
         curl -L -s -o data/res.json "${BASE_URL}"
  
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/res.json
        git commit -m "Update Google Sheets data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
